name: apptemplate

on: 
  workflow_dispatch:

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.4.1
  ACR_NAME: acrshobhitdemo
  ACR_REPO_NAME: helm/apptemplate

jobs:
  build:
    name: publish acr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        #with:
         # version: ${{ env.HELM_VERSION_TO_INSTALL }}# default is latest
      - name: validate Chart
        run: |
          helm lint ./.github/workflows/charts/apptemplate
      - name: Helm Package
        run: |
          helm package ./.github/workflows/charts/apptemplate
              
      - name: login to acr using helm
        run: |
          export HELM_EXPERIMENTAL_OCI=1
          # Helm Login to ACR
          echo '${{ secrets.REGISTRY_PASSWORD }}' | helm registry login ${{ secrets.REGISTRY_LOGIN_SERVER }} --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin 

      - name: save helm chart to local registry
        run: |
          helm chart save ./.github/workflows/charts/apptemplate ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.ACR_REPO_NAME }}:latest
      
      - name: publish chart to acr
        run: |
          helm chart push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.ACR_REPO_NAME }}:latest
