name: Pull-Request-Closed
on:
  pull_request:
    types:  [closed]
 
env:
  APP_NAME: mymicroservice
  ACR_HELM_REPO_NAME: helm/apptemplate
  ACR_HELM_CHART_NAME: apptemplate
  AKS_NAME: aksclusterdemo
  HOST_URL: pr-review.liventuspoc.com
jobs:
  build:
    name: Remove_Preview_Environment
    #if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
     
    - name: 'generate version tags'
      id: vars
      run: |
         echo ::set-output name=version_tag::$(git rev-parse --short=7 ${{ github.sha }})
         echo  Version-${{ steps.vars.outputs.version_tag }}
         echo ::set-output name=url_tag::pr-${{ env.APP_NAME }}-${{ github.event.number }}
         echo  URL TAG -${{ steps.vars.outputs.url_tag }}
         echo ::set-output name=pr_url::${{ env.APP_NAME }}-${{ github.event.number }}.${{env.HOST_URL}}
         echo  PR URL-${{ steps.vars.outputs.pr_url }}

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Login to AKS
      run: |
          az aks get-credentials -n ${{ env.AKS_NAME }} -g ${{ secrets.RESOURCE_GROUP }} --admin
     
    - name: Delete Helm Chart
      run: helm delete ${{ steps.vars.outputs.url_tag }} --namespace ${{ steps.vars.outputs.url_tag }}

    - name: Delete Namespace
      if: always()
      run: kubectl delete namespace ${{ steps.vars.outputs.url_tag }}
            
   